---
abstract: "Toolforge Mix'n'match tool object print routines."
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Toolforge-MixNMatch-Print
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Indent: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Toolforge-MixNMatch-Print/issues
  homepage: https://github.com/michal-josef-spacek/Toolforge-MixNMatch-Print
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Toolforge-MixNMatch-Print
version: '0.01'
